dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
before_install:
- openssl aes-256-cbc -K $encrypted_96405f5a4310_key -iv $encrypted_96405f5a4310_iv
  -in .travis/gcloud-app-engine-key.json.enc -out gcloud-app-engine-key.json -d
install:
- pip install pipenv
- pipenv run pip install pip==18.0 # Temp Work Around
- pipenv install
script: flask test --coverage
after_script: codecov

jobs:
  include:
  - stage: deploy
    deploy:
      provider: gae
      keyfile: gcloud-app-engine-key.json
      project: tubee-253706
