os: linux
dist: bionic
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  # - pip install -r requirements.txt
  # - pip install -r dev-requirements.txt
  - pip install pipenv
  - pipenv install --dev
script:
  - flask test --coverage
after_script: codecov
# jobs:
#   include:
#     - stage: deploy
#       before_deploy:
#         # Unzip
#         - openssl aes-256-cbc -K $encrypted_d0185b7b97bc_key -iv $encrypted_d0185b7b97bc_iv
#           -in .travis/deploy_files.tar.gz.enc -out deploy_files.tar.gz -d
#         - tar xvfz deploy_files.tar.gz
#         # client_secret & gunicorn config
#         - mkdir instance
#         - mv client_secret.json instance/client_secret.json
#         - cp deploy/gae-gunicorn.conf.py instance/gunicorn.conf.py
#         # .env & .gcloudignore
#         - DEPLOY_KEY=`openssl rand -base64 29 | tr -d "=+/" | cut -c1-25`
#         - sed -i '/DEPLOY_KEY=/s/$/'"$DEPLOY_KEY"'/' env
#         - mv env .env
#         - mv gcloudignore .gcloudignore
#         # app.yaml
#         - cp deploy/gae-app.yaml app.yaml
#       deploy:
#         provider: gae
#         keyfile: gcloud-app-engine-key.json
#         project: tubee-253706
#         skip_cleanup: true
#       after_deploy:
#         - curl -X GET 'https://tubee.tomy.me/api/deploy?key='$DEPLOY_KEY
