dist: xenial
language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
script: flask test --coverage
before_install:
- openssl aes-256-cbc -K $encrypted_96405f5a4310_key -iv $encrypted_96405f5a4310_iv
  -in .travis/gcloud-app-engine-key.json.enc -out gcloud-app-engine-key.json -d
deploy:
  provider: gae
  keyfile: gcloud-app-engine-key.json
  project: tubee-253706
after_script: codecov
