dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
# before_install:
install:
- pip install pipenv
- pipenv run pip install pip==18.0 # Temp Work Around
- pipenv install
script: flask test --coverage
after_script: codecov
jobs:
  include:
  - stage: deploy
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_160cde0a2a6f_key -iv $encrypted_160cde0a2a6f_iv
      -in .travis/deploy_files.tar.enc -out deploy_files.tar -d
    - tar xvf deploy_files.tar
    - mkdir instance
    - mv client_secret.json instance/client_secret.json
    - cp deploy/gae-gunicorn.conf.py gunicorn.conf.py
    - pipenv run pip freeze > requirements.txt
    deploy:
      provider: gae
      keyfile: gcloud-app-engine-key.json
      project: tubee-253706
    # after_deploy:
    # - (Find a way to run db upgrade)
