language: python
python:
#   - 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi:app --enable-threads
  - gunicorn -b 0.0.0.0:5000 wsgi:app

after_script:
  - codecov
