language: python
python:
#   - 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -c "print('Hello Travis')"
