language: python
python:
matrix:
    include:
        - python: 3.7
            dist: xenial
            sudo: true

install:
    - pip install -r requirements.txt

# command to run tests
script:
    - python -c "print('Hello Travis')"

after_script:
    - codecov
