language: python
python:
  - "3.6"
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements.txt
script:
- python -c "print('Hello Travis')"
- flask test --coverage
after_script:
- codecov