version: "3.8"

services:
  tubee:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/tubee"
  celery:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    volumes:
      - ".:/usr/src/tubee"
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
  # redis:
  #   ports:
  #     - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
