version: "3.7"

services:
  web:
    build: .
    command: flask run -h 0.0.0.0
    volumes:
      - .:/usr/src/tubee/
    ports:
      - 0.0.0.0:5000:5000
    env_file:
      - docker.dev.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - celery
      - redis
      # - db
  celery:
    build: .
    command: celery worker --app=celery_worker.celery --loglevel=info
    # command: celery worker --app=celery_worker.celery --loglevel=info -E
    volumes:
      - .:/usr/src/tubee/
    env_file:
      - docker.dev.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:6.0
    # build:
    #   context: ./deploy
    #   dockerfile: redis.Dockerfile
    command: redis-server --appendonly yes --bind 0.0.0.0
    expose:
      - 6379
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis_data:/data
  # db:
  #   image: postgres:12-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_flask
  #     - POSTGRES_PASSWORD=hello_flask
  #     - POSTGRES_DB=hello_flask_dev

volumes:
  redis_data:
  # postgres_data:
