version: "3.8"

services:
  nginx:
    image: "tomy0000000/nginx:1.17-1.2"
    depends_on:
      - "tubee"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - application:/usr/share/nginx/tubee
  tubee:
    command: "gunicorn --config conf/gunicorn.conf.py app:app"
    env_file:
      - "instance/production.env"
    environment:
      FLASK_ENV: "production"
    restart: "always"
    volumes:
      - application:/usr/src/tubee
  celery:
    command: "celery worker --app=celery_worker.celery --loglevel=info"
    env_file:
      - "instance/production.env"
    environment:
      FLASK_ENV: "production"
    restart: "always"
  postgres:
    env_file:
      - "instance/production.env"
    restart: "always"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  application:
  postgres_data:
