version: "3.8"

services:
  tubee:
    depends_on:
      - "celery"
      - "redis"
      - "postgres"
    image: "tomy0000000/tubee"
  celery:
    depends_on:
      - "redis"
    image: "tomy0000000/tubee"
  redis:
    command: "redis-server --bind 0.0.0.0"
    image: "redis:6.0"
    sysctls:
      - "net.core.somaxconn=511"
  postgres:
    image: "postgres:12-alpine"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data:
