version: "3.8"

services:
  celery:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    command:
      [
        "watchmedo",
        "auto-restart",
        "--directory=./",
        "--pattern=*.py",
        "--recursive",
        "--",
        "celery",
        "--app=celery_worker.celery",
        "worker",
        "--loglevel=info",
        "--statedb=/usr/src/tubee/instance/celery/%n.state",
      ]
    depends_on:
      - "rabbitmq"
    image: "tomy0000000/tubee"
    env_file:
      - ".env"
    environment:
      FLASK_ENV: "development"
    network_mode: "host"
    volumes:
      - ".:/usr/src/tubee"
  rabbitmq:
    hostname: "tubee-rabbitmq"
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
  postgres:
    env_file:
      - ".env"
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  rabbitmq_data:
  postgres_data:
