version: "3.8"

services:
    tubee:
        depends_on:
            - "celery"
            - "rabbitmq"
            - "postgres"
        image: "tomy0000000/tubee"
        volumes:
            - "./logs:/usr/src/tubee/logs"
    celery:
        depends_on:
            - "rabbitmq"
        image: "tomy0000000/tubee"
        volumes:
            - "./logs:/usr/src/tubee/logs"
    rabbitmq:
        hostname: "tubee-rabbitmq"
        image: "rabbitmq:latest"
        volumes:
            - "rabbitmq_data:/var/lib/rabbitmq"
    postgres:
        image: "postgres:12-alpine"
        volumes:
            - "postgres_data:/var/lib/postgresql/data"

volumes:
    rabbitmq_data:
    postgres_data:
