# app.yaml
runtime: python37
env: standard
instance_class: F1
entrypoint: gunicorn --config instance/gunicorn.conf.py app:app
handlers:
  - url: /static/(.*)
    static_files: tubee/static/\1
    require_matching_file: false
    upload: tubee/static/.*
  - url: /.*
    script: auto
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
